Feature/docker secrets
RSOA-WEITI-2020/AuthService pull request #3
Opened 2020-05-12 17:34 UTC by RobPiwowarek

2020-05-12 17:35 UTC, RobPiwowarek commented
Added 2 placeholder secrets through repository settings pubk privk

2020-05-28 18:07 UTC, FrozenPear42 requested changes

2020-05-28 18:07 UTC, Grushenko commented on .github/workflows/publish.yml
> +          docker build --build-arg PUBLIC_KEY=${{secrets.pubk}} --build-arg PRIVATE_KEY=${{secrets.privk}}-t $CONTAINER_LOWERCASE .
Missing space before `-t`.
You also have to modify  Docker file save those args to file and then copy it with exisitng `COPY` commands

2020-06-23 13:46 UTC, RobPiwowarek commented on .github/workflows/publish.yml
> +          docker build --build-arg PUBLIC_KEY=${{secrets.pubk}} --build-arg PRIVATE_KEY=${{secrets.privk}}-t $CONTAINER_LOWERCASE .
so the existing COPY which copies dockerfile public/private key wont work?

2020-06-23 14:49 UTC, FrozenPear42 approved these changes
LGTM
![ap,550x550,12x16,1,transparent,t u7](https://user-images.githubusercontent.com/1392304/85418779-837a8c80-b571-11ea-907a-415dfe41aee9.png)

2020-06-23 14:50 UTC, merged